databases:
  - name: movie-theater-db
    plan: free
    databaseName: movie_theater
    user: movie_theater

services:
  - type: web
    plan: free
    name: movie-theater-booking
    runtime: python
    rootDir: homework2/student/movie_theater_booking
    buildCommand: './build.sh'
    startCommand: 'gunicorn movie_theater_booking.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie-theater-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.12.3
