# Generated by Django 4.2.11 on 2026-02-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seat_layout'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', to='bookings.seat'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
    ]
