# Generated by Django 4.2.11 on 2026-03-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_unique_together_booking_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
